//#line 2 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
// *********************************************************
// 
// File autogenerated for the projector_calibration package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

/***********************************************************
 * Software License Agreement (BSD License)
 *
 *  Copyright (c) 2008, Willow Garage, Inc.
 *  All rights reserved.
 *
 *  Redistribution and use in source and binary forms, with or without
 *  modification, are permitted provided that the following conditions
 *  are met:
 *
 *   * Redistributions of source code must retain the above copyright
 *     notice, this list of conditions and the following disclaimer.
 *   * Redistributions in binary form must reproduce the above
 *     copyright notice, this list of conditions and the following
 *     disclaimer in the documentation and/or other materials provided
 *     with the distribution.
 *   * Neither the name of the Willow Garage nor the names of its
 *     contributors may be used to endorse or promote products derived
 *     from this software without specific prior written permission.
 *
 *  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 *  "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 *  LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 *  FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 *  COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 *  INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 *  BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 *  LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 *  CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 *  LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 *  ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 *  POSSIBILITY OF SUCH DAMAGE.
 ***********************************************************/

// Author: Blaise Gassend


#ifndef __projector_calibration__VISUALIZATION_PARAMSCONFIG_H__
#define __projector_calibration__VISUALIZATION_PARAMSCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/config_init_mutex.h>

namespace projector_calibration
{
  class visualization_paramsConfigStatics;
  
  class visualization_paramsConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(visualization_paramsConfig &config, const visualization_paramsConfig &max, const visualization_paramsConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const visualization_paramsConfig &config1, const visualization_paramsConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, visualization_paramsConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const visualization_paramsConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, visualization_paramsConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const visualization_paramsConfig &config) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T visualization_paramsConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (visualization_paramsConfig::* field);

      virtual void clamp(visualization_paramsConfig &config, const visualization_paramsConfig &max, const visualization_paramsConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const visualization_paramsConfig &config1, const visualization_paramsConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, visualization_paramsConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const visualization_paramsConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, visualization_paramsConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const visualization_paramsConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }
    };

//#line 11 "../cfg/params.cfg"
      double cell_length_cm;
//#line 12 "../cfg/params.cfg"
      int hist_length;
//#line 15 "../cfg/params.cfg"
      double update_weight;
//#line 18 "../cfg/params.cfg"
      int sim_iter_cnt;
//#line 19 "../cfg/params.cfg"
      double sim_viscosity;
//#line 21 "../cfg/params.cfg"
      double max_update_dist;
//#line 24 "../cfg/params.cfg"
      double ant_steepness;
//#line 25 "../cfg/params.cfg"
      double ant_cost_factor;
//#line 26 "../cfg/params.cfg"
      int ant_use_four;
//#line 27 "../cfg/params.cfg"
      double ant_uphill_factor;
//#line 28 "../cfg/params.cfg"
      double ant_hillside_factor;
//#line 29 "../cfg/params.cfg"
      double ant_path_length_factor;
//#line 31 "../cfg/params.cfg"
      int ant_use_smoothing;
//#line 34 "../cfg/params.cfg"
      double light_pos;
//#line 138 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        if ((*i)->fromMessage(msg, *this))
          count++;
      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("visualization_paramsConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toMessage(msg, *this);
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      __toMessage__(msg, __param_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->fromServer(nh, *this);
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const visualization_paramsConfig &__max__ = __getMax__();
      const visualization_paramsConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const visualization_paramsConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const visualization_paramsConfig &__getDefault__();
    static const visualization_paramsConfig &__getMax__();
    static const visualization_paramsConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    
  private:
    static const visualization_paramsConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void visualization_paramsConfig::ParamDescription<std::string>::clamp(visualization_paramsConfig &config, const visualization_paramsConfig &max, const visualization_paramsConfig &min) const
  {
    return;
  }

  class visualization_paramsConfigStatics
  {
    friend class visualization_paramsConfig;
    
    visualization_paramsConfigStatics()
    {
//#line 11 "../cfg/params.cfg"
      __min__.cell_length_cm = 0.4;
//#line 11 "../cfg/params.cfg"
      __max__.cell_length_cm = 5.0;
//#line 11 "../cfg/params.cfg"
      __default__.cell_length_cm = 0.4;
//#line 11 "../cfg/params.cfg"
      __param_descriptions__.push_back(visualization_paramsConfig::AbstractParamDescriptionConstPtr(new visualization_paramsConfig::ParamDescription<double>("cell_length_cm", "double", 0, "cell length in cm", "", &visualization_paramsConfig::cell_length_cm)));
//#line 12 "../cfg/params.cfg"
      __min__.hist_length = 1;
//#line 12 "../cfg/params.cfg"
      __max__.hist_length = 10;
//#line 12 "../cfg/params.cfg"
      __default__.hist_length = 2;
//#line 12 "../cfg/params.cfg"
      __param_descriptions__.push_back(visualization_paramsConfig::AbstractParamDescriptionConstPtr(new visualization_paramsConfig::ParamDescription<int>("hist_length", "int", 0, "# Frames meaned", "", &visualization_paramsConfig::hist_length)));
//#line 15 "../cfg/params.cfg"
      __min__.update_weight = 0.0;
//#line 15 "../cfg/params.cfg"
      __max__.update_weight = 1.0;
//#line 15 "../cfg/params.cfg"
      __default__.update_weight = 0.1;
//#line 15 "../cfg/params.cfg"
      __param_descriptions__.push_back(visualization_paramsConfig::AbstractParamDescriptionConstPtr(new visualization_paramsConfig::ParamDescription<double>("update_weight", "double", 0, "update weight", "", &visualization_paramsConfig::update_weight)));
//#line 18 "../cfg/params.cfg"
      __min__.sim_iter_cnt = 1;
//#line 18 "../cfg/params.cfg"
      __max__.sim_iter_cnt = 30;
//#line 18 "../cfg/params.cfg"
      __default__.sim_iter_cnt = 10;
//#line 18 "../cfg/params.cfg"
      __param_descriptions__.push_back(visualization_paramsConfig::AbstractParamDescriptionConstPtr(new visualization_paramsConfig::ParamDescription<int>("sim_iter_cnt", "int", 0, "# iterations per Frame", "", &visualization_paramsConfig::sim_iter_cnt)));
//#line 19 "../cfg/params.cfg"
      __min__.sim_viscosity = 0.0;
//#line 19 "../cfg/params.cfg"
      __max__.sim_viscosity = 1.0;
//#line 19 "../cfg/params.cfg"
      __default__.sim_viscosity = 0.9;
//#line 19 "../cfg/params.cfg"
      __param_descriptions__.push_back(visualization_paramsConfig::AbstractParamDescriptionConstPtr(new visualization_paramsConfig::ParamDescription<double>("sim_viscosity", "double", 0, "viscosity", "", &visualization_paramsConfig::sim_viscosity)));
//#line 21 "../cfg/params.cfg"
      __min__.max_update_dist = 0.0;
//#line 21 "../cfg/params.cfg"
      __max__.max_update_dist = 0.2;
//#line 21 "../cfg/params.cfg"
      __default__.max_update_dist = 0.1;
//#line 21 "../cfg/params.cfg"
      __param_descriptions__.push_back(visualization_paramsConfig::AbstractParamDescriptionConstPtr(new visualization_paramsConfig::ParamDescription<double>("max_update_dist", "double", 0, "max_update_dist", "", &visualization_paramsConfig::max_update_dist)));
//#line 24 "../cfg/params.cfg"
      __min__.ant_steepness = 0.0;
//#line 24 "../cfg/params.cfg"
      __max__.ant_steepness = 90.0;
//#line 24 "../cfg/params.cfg"
      __default__.ant_steepness = 45.0;
//#line 24 "../cfg/params.cfg"
      __param_descriptions__.push_back(visualization_paramsConfig::AbstractParamDescriptionConstPtr(new visualization_paramsConfig::ParamDescription<double>("ant_steepness", "double", 0, "ant_max_angle", "", &visualization_paramsConfig::ant_steepness)));
//#line 25 "../cfg/params.cfg"
      __min__.ant_cost_factor = 0.0;
//#line 25 "../cfg/params.cfg"
      __max__.ant_cost_factor = 10.0;
//#line 25 "../cfg/params.cfg"
      __default__.ant_cost_factor = 3.0;
//#line 25 "../cfg/params.cfg"
      __param_descriptions__.push_back(visualization_paramsConfig::AbstractParamDescriptionConstPtr(new visualization_paramsConfig::ParamDescription<double>("ant_cost_factor", "double", 0, "ant_cost_factor", "", &visualization_paramsConfig::ant_cost_factor)));
//#line 26 "../cfg/params.cfg"
      __min__.ant_use_four = 0;
//#line 26 "../cfg/params.cfg"
      __max__.ant_use_four = 1;
//#line 26 "../cfg/params.cfg"
      __default__.ant_use_four = 1;
//#line 26 "../cfg/params.cfg"
      __param_descriptions__.push_back(visualization_paramsConfig::AbstractParamDescriptionConstPtr(new visualization_paramsConfig::ParamDescription<int>("ant_use_four", "int", 0, "ant_use_four", "", &visualization_paramsConfig::ant_use_four)));
//#line 27 "../cfg/params.cfg"
      __min__.ant_uphill_factor = 0.0;
//#line 27 "../cfg/params.cfg"
      __max__.ant_uphill_factor = 10.0;
//#line 27 "../cfg/params.cfg"
      __default__.ant_uphill_factor = 3.0;
//#line 27 "../cfg/params.cfg"
      __param_descriptions__.push_back(visualization_paramsConfig::AbstractParamDescriptionConstPtr(new visualization_paramsConfig::ParamDescription<double>("ant_uphill_factor", "double", 0, "ant_uphill_factor", "", &visualization_paramsConfig::ant_uphill_factor)));
//#line 28 "../cfg/params.cfg"
      __min__.ant_hillside_factor = 0.0;
//#line 28 "../cfg/params.cfg"
      __max__.ant_hillside_factor = 50.0;
//#line 28 "../cfg/params.cfg"
      __default__.ant_hillside_factor = 14.0;
//#line 28 "../cfg/params.cfg"
      __param_descriptions__.push_back(visualization_paramsConfig::AbstractParamDescriptionConstPtr(new visualization_paramsConfig::ParamDescription<double>("ant_hillside_factor", "double", 0, "ant_hillside_factor", "", &visualization_paramsConfig::ant_hillside_factor)));
//#line 29 "../cfg/params.cfg"
      __min__.ant_path_length_factor = 0.0;
//#line 29 "../cfg/params.cfg"
      __max__.ant_path_length_factor = 50.0;
//#line 29 "../cfg/params.cfg"
      __default__.ant_path_length_factor = 14.0;
//#line 29 "../cfg/params.cfg"
      __param_descriptions__.push_back(visualization_paramsConfig::AbstractParamDescriptionConstPtr(new visualization_paramsConfig::ParamDescription<double>("ant_path_length_factor", "double", 0, "ant_path_length_factor", "", &visualization_paramsConfig::ant_path_length_factor)));
//#line 31 "../cfg/params.cfg"
      __min__.ant_use_smoothing = 0;
//#line 31 "../cfg/params.cfg"
      __max__.ant_use_smoothing = 1;
//#line 31 "../cfg/params.cfg"
      __default__.ant_use_smoothing = 0;
//#line 31 "../cfg/params.cfg"
      __param_descriptions__.push_back(visualization_paramsConfig::AbstractParamDescriptionConstPtr(new visualization_paramsConfig::ParamDescription<int>("ant_use_smoothing", "int", 0, "ant_use_smoothing", "", &visualization_paramsConfig::ant_use_smoothing)));
//#line 34 "../cfg/params.cfg"
      __min__.light_pos = -2.0;
//#line 34 "../cfg/params.cfg"
      __max__.light_pos = 2.0;
//#line 34 "../cfg/params.cfg"
      __default__.light_pos = 0.0;
//#line 34 "../cfg/params.cfg"
      __param_descriptions__.push_back(visualization_paramsConfig::AbstractParamDescriptionConstPtr(new visualization_paramsConfig::ParamDescription<double>("light_pos", "double", 0, "light_pos", "", &visualization_paramsConfig::light_pos)));
//#line 239 "/opt/ros/electric/stacks/driver_common/dynamic_reconfigure/templates/ConfigType.h"
    
      for (std::vector<visualization_paramsConfig::AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); i++)
        __description_message__.parameters.push_back(**i);
      __max__.__toMessage__(__description_message__.max, __param_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__); 
    }
    std::vector<visualization_paramsConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    visualization_paramsConfig __max__;
    visualization_paramsConfig __min__;
    visualization_paramsConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;
    static const visualization_paramsConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static visualization_paramsConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &visualization_paramsConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const visualization_paramsConfig &visualization_paramsConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const visualization_paramsConfig &visualization_paramsConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const visualization_paramsConfig &visualization_paramsConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<visualization_paramsConfig::AbstractParamDescriptionConstPtr> &visualization_paramsConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const visualization_paramsConfigStatics *visualization_paramsConfig::__get_statics__()
  {
    const static visualization_paramsConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = visualization_paramsConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __VISUALIZATION_PARAMSRECONFIGURATOR_H__
